// src/data/extensions.js
export const extensions = [
    {
        id: 1,
        title: "Quick Checkout / Onepage Checkout",
        price: "$29.99",
        rating: 5,
        reviews: 25,
        badge: "BESTSELLER",
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 2,
        title: "Restrict Payment Methods",
        price: "$44.99",
        rating: 5,
        reviews: 25,
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 3,
        title: "Formula-Based Shipping",
        price: "$33.99",
        rating: 5,
        reviews: 24,
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 4,
        title: "Restrict Shipping Methods",
        price: "$44.99",
        rating: 5,
        reviews: 24,
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 5,
        title: "Automated Newsletter - Fully Automated Newsletter",
        price: "$34.99",
        rating: 5,
        reviews: 24,
        badge: "BESTSELLER",
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 6,
        title: "SEO Structured Data - Rich Snippets - Microdata",
        price: "$30.00",
        rating: 4,
        reviews: 23,
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 7,
        title: "Postcode-Based Shipping",
        price: "$22.99",
        rating: 5,
        reviews: 18,
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 8,
        title: "Free Shipping Plus",
        price: "$33.99",
        rating: 4,
        reviews: 17,
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 9,
        title: "Complete Product Import Export MultiLanguage",
        price: "$29.99",
        rating: 5,
        reviews: 17,
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 10,
        title: "Product Option Color Image",
        price: "$29.99",
        rating: 5,
        reviews: 17,
        badge: "FEATURED",
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 11,
        title: "iAnalytics - OpenCart Analytics. Reinvented.",
        price: "$49.99",
        rating: 5,
        reviews: 17,
        badge: "BESTSELLER",
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 12,
        title: "Account Sidebar",
        price: "FREE",
        rating: 5,
        reviews: 17,
        badge: "FREE",
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 13,
        title: "Postcode-Based Shipping (Duplicate)",
        price: "$22.99",
        rating: 5,
        reviews: 18,
        image: "https://image.opencart.com/cache/5a0aed207a72b-resize-260x152.jpg",
    },
    {
        id: 14,
        title: "Free Shipping Plus (Duplicate)",
        price: "$33.99",
        rating: 4,
        reviews: 17,
        image: "https://via.placeholder.com/400x300?text=Free+Shipping+Plus+2",
    },
    {
        id: 15,
        title: "Complete Product Import Export MultiLanguage (Duplicate)",
        price: "$29.99",
        rating: 5,
        reviews: 17,
        image: "https://via.placeholder.com/400x300?text=Import+Export+2",
    },
    {
        id: 16,
        title: "Product Option Color Image (Duplicate)",
        price: "$29.99",
        rating: 5,
        reviews: 17,
        badge: "FEATURED",
        image: "https://via.placeholder.com/400x300?text=Option+Color+Image+2",
    },
    {
        id: 17,
        title: "iAnalytics - OpenCart Analytics. Reinvented. (Duplicate)",
        price: "$49.99",
        rating: 5,
        reviews: 17,
        badge: "BESTSELLER",
        image: "https://via.placeholder.com/400x300?text=iAnalytics+2",
    },
    {
        id: 18,
        title: "Account Sidebar (Duplicate)",
        price: "FREE",
        rating: 5,
        reviews: 17,
        badge: "FREE",
        image: "https://via.placeholder.com/400x300?text=Account+Sidebar+2",
    },
];
